import type {
  CharacterDescriptionOptions,
  CharacterInspiration,
  ClassGuide,
  StartingEquipmentOptions,
} from ".";

export const characterDescriptionOptions = {
  eyes: [
    "carnations",
    "earth",
    "endless ocean",
    "fire",
    "ivy",
    "lilacs",
    "night",
    "seafoam",
    "winter",
  ],
  body: [
    "broad",
    "carved",
    "curvy",
    "lanky",
    "rotund",
    "short",
    "stocky",
    "tall",
    "thin",
    "tiny",
    "toned",
  ],
  skin: [
    "ashes",
    "clover",
    "falling snow",
    "fine sand",
    "obsidian",
    "rose",
    "sapphire",
    "wisteria",
  ],
} as const satisfies CharacterDescriptionOptions;

export const classGuides = [
  {
    class: "Assassin",
    summary:
      "As an assassin, you blend expertise in stealth and a mastery over death, dealing fatal blows to the unwary with lethal accuracy.",
    suggestedTraits: {
      Agility: 2,
      Strength: -1,
      Finesse: 1,
      Instinct: 0,
      Presence: 0,
      Knowledge: 1,
    },
    suggestedPrimaryWeapon: "Katana",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Brigandine Armor",
    clothes: [
      "finely tailored",
      "hooded",
      "incognito",
      "padded for silence",
      "sinister",
      "weathered",
    ],
    attitudes: [
      "a butcher",
      "a coiled viper",
      "a hidden razor",
      "a hunter",
      "a judge",
      "a merchant",
      "an owl",
    ],
    spellCarrier: null,
  },
  {
    class: "Bard",
    summary:
      "As a bard, you know how to get people to talk, bring attention to yourself, and use words or music to influence the world around you.",
    suggestedTraits: {
      Agility: 0,
      Strength: -1,
      Finesse: 1,
      Instinct: 0,
      Presence: 2,
      Knowledge: 1,
    },
    suggestedPrimaryWeapon: "Rapier",
    suggestedSecondaryWeapon: "Small Dagger",
    suggestedArmor: "Gambeson Armor",
    clothes: [
      "extravagant",
      "fancy",
      "loud",
      "oversized",
      "ragged",
      "sleek",
      "wild",
    ],
    attitudes: [
      "a barkeep",
      "a magician",
      "a ringmaster",
      "a rock star",
      "a swashbuckler",
    ],
    spellCarrier: {
      prompt: "Your spells in",
      examples: ["songbook", "journal"],
    },
  },
  {
    class: "Brawler",
    summary:
      "As a brawler, you've honed your body into a lethal weapon, allowing you to deliver powerful strikes that intimidate your foes.",
    suggestedTraits: {
      Agility: 1,
      Strength: 1,
      Finesse: 0,
      Instinct: 2,
      Presence: 0,
      Knowledge: -1,
    },
    suggestedPrimaryWeapon: "Brawler's Strike",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Brigandine Armor",
    clothes: [
      "bright",
      "haphazard",
      "practical",
      "pristine",
      "someone else's",
      "standard-issue",
    ],
    attitudes: [
      "a flowing river",
      "a golden retriever",
      "a loose cannon",
      "a parent",
      "a protector",
      "a veteran",
    ],
    spellCarrier: null,
  },
  {
    class: "Druid",
    summary:
      "As a druid, you are a force of nature, preserving the balance of life and death by channeling the wilds themselves through you.",
    suggestedTraits: {
      Agility: 1,
      Strength: 0,
      Finesse: 1,
      Instinct: 2,
      Presence: -1,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Shortstaff",
    suggestedSecondaryWeapon: "Round Shield",
    suggestedArmor: "Leather Armor",
    clothes: [
      "camouflaged",
      "grown",
      "loose",
      "natural",
      "patchwork",
      "regal",
      "scraps",
    ],
    attitudes: ["a firecracker", "a fox", "a guide", "a hippie", "a witch"],
    spellCarrier: null,
  },
  {
    class: "Guardian",
    summary:
      "As a guardian, you run into danger to protect your party, keeping watch over those who might not survive without you there.",
    suggestedTraits: {
      Agility: 1,
      Strength: 2,
      Finesse: -1,
      Instinct: 0,
      Presence: 1,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Battleaxe",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Chainmail Armor",
    clothes: [
      "casual",
      "intricate",
      "loose",
      "padded",
      "royal",
      "tactical",
      "weathered",
    ],
    attitudes: [
      "a captain",
      "a caretaker",
      "an elephant",
      "a general",
      "a wrestler",
    ],
    spellCarrier: null,
  },
  {
    class: "Ranger",
    summary:
      "As a ranger, your keen eyes and graceful haste make you indespensible when tracking down enemies and navigating the wilds.",
    suggestedTraits: {
      Agility: 2,
      Strength: 0,
      Finesse: 1,
      Instinct: 1,
      Presence: -1,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Shortbow",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Leather Armor",
    clothes: [
      "flowing",
      "muted",
      "natural",
      "stained",
      "tactical",
      "tight",
      "woven",
    ],
    attitudes: [
      "a child",
      "a ghost",
      "a survivalist",
      "a teacher",
      "a watchdog",
    ],
    spellCarrier: null,
  },
  {
    class: "Rogue",
    summary:
      "As a rogue, you have experience fighting with your blade as well as your wit, preferring to move quickly and fight quietly.",
    suggestedTraits: {
      Agility: 1,
      Strength: -1,
      Finesse: 2,
      Instinct: 0,
      Presence: 1,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Dagger",
    suggestedSecondaryWeapon: "Small Dagger",
    suggestedArmor: "Gambeson Armor",
    clothes: [
      "clean",
      "dark",
      "inconspicuous",
      "leather",
      "scary",
      "tactical",
      "tight",
    ],
    attitudes: [
      "a bandit",
      "a con artist",
      "a gambler",
      "a mob boss",
      "a pirate",
    ],
    spellCarrier: null,
  },
  {
    class: "Seraph",
    summary:
      "As a seraph, you've taken a vow to a god who helps you channel sacred arcane power to keep your party on their feet.",
    suggestedTraits: {
      Agility: 0,
      Strength: 2,
      Finesse: 0,
      Instinct: 1,
      Presence: 1,
      Knowledge: -1,
    },
    suggestedPrimaryWeapon: "Hallowed Axe",
    suggestedSecondaryWeapon: "Round Shield",
    suggestedArmor: "Chainmail Armor",
    clothes: [
      "glowing",
      "rippling",
      "ornate",
      "tight",
      "modest",
      "strange",
      "natural",
    ],
    attitudes: [
      "an angel",
      "a doctor",
      "an evangelist",
      "a monk",
      "a priest",
    ],
    spellCarrier: null,
  },
  {
    class: "Sorcerer",
    summary:
      "As a sorcerer, you were born with innate magical power, and you've learned how to wield that power to get what you want.",
    suggestedTraits: {
      Agility: 0,
      Strength: -1,
      Finesse: 1,
      Instinct: 2,
      Presence: 1,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Dualstaff",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Gambeson Armor",
    clothes: [
      "always moving",
      "flamboyant",
      "inconspicuous",
      "layered",
      "ornate",
      "tight",
    ],
    attitudes: [
      "a celebrity",
      "a commander",
      "a politician",
      "a prankster",
      "a wolf in sheep's clothing",
    ],
    spellCarrier: null,
  },
  {
    class: "Warlock",
    summary:
      "As a warlock, you've pledged your life to an otherworldly patron in exchange for extraordinary power.",
    suggestedTraits: {
      Agility: 1,
      Strength: -1,
      Finesse: 0,
      Instinct: 1,
      Presence: 2,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Scimitar",
    suggestedSecondaryWeapon: "Fighting Cloak",
    suggestedArmor: "Mage Robes",
    clothes: [
      "billowing",
      "lavish",
      "luminous",
      "mended",
      "neat",
      "sacred",
      "shadowy",
      "smoking",
    ],
    attitudes: [
      "a coming storm",
      "a devotee",
      "a hot mess",
      "a jester",
      "a live wire",
      "a monarch",
      "a soothsayer",
    ],
    spellCarrier: null,
  },
  {
    class: "Warrior",
    summary:
      "As a warrior, you run into battle without hestation or caution, knowing you can strike down whatever enemy stands in your path.",
    suggestedTraits: {
      Agility: 2,
      Strength: 1,
      Finesse: 0,
      Instinct: 1,
      Presence: -1,
      Knowledge: 0,
    },
    suggestedPrimaryWeapon: "Longsword",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Chainmail Armor",
    clothes: [
      "bold",
      "patched",
      "reinforced",
      "royal",
      "sleek",
      "sparing",
      "weathered",
    ],
    attitudes: [
      "a bull",
      "a dedicated soldier",
      "a gladiator",
      "a hero",
      "a hired hand",
    ],
    spellCarrier: null,
  },
  {
    class: "Witch",
    summary:
      "As a witch, you use detailed knowledge of magical craft to weave spells that bolster your allies and hex your enemies.",
    suggestedTraits: {
      Agility: 0,
      Strength: -1,
      Finesse: 0,
      Instinct: 2,
      Presence: 1,
      Knowledge: 1,
    },
    suggestedPrimaryWeapon: "Casting Dagger",
    suggestedSecondaryWeapon: "Rune Shield",
    suggestedArmor: "Mage Robes",
    clothes: [
      "diaphanous",
      "flowing",
      "foreboding",
      "ragged",
      "stately",
      "uniquely patterned",
    ],
    attitudes: [
      "a candle flame",
      "a cat",
      "a doctor",
      "an old tree",
      "an oracle",
      "a spider",
      "a sunny day",
    ],
    spellCarrier: {
      prompt: "What you use for your craft",
      examples: ["a handwritten journal", "runestones"],
    },
  },
  {
    class: "Wizard",
    summary:
      "As a wizard, you've become familiar with the arcane through the relentless study of grimoires and other tools of magic.",
    suggestedTraits: {
      Agility: -1,
      Strength: 0,
      Finesse: 0,
      Instinct: 1,
      Presence: 1,
      Knowledge: 2,
    },
    suggestedPrimaryWeapon: "Greatstaff",
    suggestedSecondaryWeapon: null,
    suggestedArmor: "Leather Armor",
    clothes: [
      "beautiful",
      "clean",
      "common",
      "flowing",
      "layered",
      "patchwork",
      "tight",
    ],
    attitudes: [
      "an eccentric",
      "a librarian",
      "a lit fuse",
      "a philosopher",
      "a professor",
    ],
    spellCarrier: {
      prompt: "Your spells in",
      examples: ["large tomes", "tarot cards"],
    },
  },
] as const satisfies readonly ClassGuide[];

export const hopeAndFearStartingEquipment = {
  primaryWeapons: [
    "Katana",
    "Brass Knuckles",
    "Scimitar",
    "Twisted Dagger",
    "Whipsword",
    "Rope Dart",
    "Brightsword",
    "Shadowblade",
    "Enchanted Chakram",
    "Casting Dagger",
    "Runelock Pistol",
    "Arcane Rifle",
  ],
  secondaryWeapons: [
    "Hatchet",
    "Offhand Brass Knuckles",
    "Throwing Knives",
    "Fighting Cloak",
    "Rune Shield",
    "Focus Runes",
  ],
  armor: [
    "Mage Robes",
    "Brigandine Armor",
    "Scale Mail Armor",
    "Banded Armor",
  ],
} as const satisfies StartingEquipmentOptions;

export const characterInspiration = {
  firstNames: [
    "Alucard",
    "Ambrose",
    "Ash",
    "Bellamy",
    "Calder",
    "Calypso",
    "Chartreuse",
    "Clover",
    "Dahlia",
    "Darrow",
    "Deacon",
    "Elowen",
    "Emrys",
    "Fable",
    "Fiorella",
    "Flynn",
    "Gatlin",
    "Gerard",
    "Hadron",
    "Harlow",
    "Indigo",
    "Isla",
    "Jaden",
    "Kai",
    "Kismet",
    "Leo",
    "Mika",
    "Moon",
    "Nyx",
    "Orna",
    "Phaedra",
    "Quill",
    "Rani",
    "Raphael",
    "Reza",
    "Roux",
    "Saffron",
    "Sierra",
    "Skye",
    "Talon",
    "Thea",
    "Triton",
    "Vala",
    "Velo",
    "Wisteria",
    "Yanelle",
    "Zahara",
  ],
  familyNames: [
    "Abbot",
    "Advani",
    "Agoston",
    "Baptiste",
    "Belgarde",
    "Blossom",
    "Chance",
    "Covault",
    "Dawn",
    "Dennison",
    "Drayer",
    "Emrick",
    "Foley",
    "Fury",
    "Grove",
    "Hartley",
    "Humfleet",
    "Hyland",
    "Ikeda",
    "Jones",
    "Jordon",
    "Kaan",
    "Knoth",
    "Lagrange",
    "Lockamy",
    "Lyon",
    "Marche",
    "Merrell",
    "Newland",
    "Novak",
    "Orwick",
    "Overholt",
    "Pray",
    "Rathbone",
    "Rose",
    "Seagrave",
    "Spurlock",
    "Thorn",
    "Tringle",
    "Vasquez",
    "Warren",
    "Worth",
    "York",
  ],
  regionNames: [
    "Alvyon",
    "Bloomfare",
    "Bonecross",
    "Branishar",
    "Cloud Isles",
    "Davesh Pass",
    "End of Journeys",
    "Fearhold",
    "Ir'thandir",
    "Mountains of Creation",
    "Nocturne",
    "Revenance",
    "Shattered Peaks",
    "South Choir",
    "Sunbearer's Crescent",
    "Watcher's Ravine",
    "Wilting Valley",
    "Xuria",
  ],
  placeNames: [
    "Balking Tide",
    "Black Willow",
    "Crow's Nest",
    "Dire Reach",
    "Figero",
    "Fool's Gold",
    "Golden Goose",
    "Hearthbreak",
    "Hollow Keep",
    "Idle Fiend",
    "Kross",
    "Limping Liar",
    "Mettler's Make",
    "Nero's Compass",
    "Netherwell",
    "Parting Gift",
    "Quiet Magnitude",
    "Roaming Way",
    "Salute",
    "Wicked Smile",
  ],
  experiences: {
    backgrounds: ["Bodyguard", "Con Artist", "Merchant", "Noble", "Pirate"],
    characteristics: ["Affable", "Intimidating", "Sticky Fingers", "Survivor"],
    specialties: ["Healer", "Inventor", "Navigator", "Swashbuckler"],
    skills: ["Barter", "Quick Hands", "Repair", "Tracker"],
    phrases: [
      "Catch Me If You Can",
      "Hold the Line",
      "Nature's Friend",
      "This Is Not a Negotiation",
    ],
  },
} as const satisfies CharacterInspiration;
