import type { EnvironmentReference } from ".";

export const environmentIndex = [
  { name: "Abandoned Grove", tier: 1, type: "Exploration" },
  { name: "Abandoned Mine", tier: 1, type: "Traversal" },
  { name: "Alchemist's Abandoned Workshop", tier: 1, type: "Exploration" },
  { name: "Ambushed", tier: 1, type: "Event" },
  { name: "Ambushers", tier: 1, type: "Event" },
  { name: "Bustling Marketplace", tier: 1, type: "Social" },
  { name: "Cliffside Ascent", tier: 1, type: "Traversal" },
  { name: "Corrupted Swamp", tier: 1, type: "Traversal" },
  { name: "Cursed Graveyard", tier: 1, type: "Exploration" },
  { name: "Grand Feast", tier: 1, type: "Social" },
  { name: "Hold the Line", tier: 1, type: "Event" },
  { name: "Local Festival", tier: 1, type: "Social" },
  { name: "Local Tavern", tier: 1, type: "Social" },
  { name: "Outpost Town", tier: 1, type: "Social" },
  { name: "Raging River", tier: 1, type: "Traversal" },
  { name: "Raiding Party", tier: 1, type: "Event" },
  { name: "Beach Day", tier: 2, type: "Social" },
  { name: "Cult Ritual", tier: 2, type: "Event" },
  { name: "Deadly Dungeon", tier: 2, type: "Exploration" },
  { name: "Duel", tier: 2, type: "Event" },
  { name: "Hallowed Temple", tier: 2, type: "Social" },
  { name: "Haunted City", tier: 2, type: "Exploration" },
  { name: "Heist", tier: 2, type: "Event" },
  { name: "Masquerade Ball", tier: 2, type: "Social" },
  { name: "Mountain Pass", tier: 2, type: "Traversal" },
  { name: "Ocean Voyage", tier: 2, type: "Traversal" },
  { name: "Vast Desert", tier: 2, type: "Traversal" },
  { name: "Witch's Hut", tier: 2, type: "Exploration" },
  { name: "Archmage's Tower", tier: 3, type: "Exploration" },
  { name: "Astral Realm", tier: 3, type: "Traversal" },
  { name: "Burning Heart of the Woods", tier: 3, type: "Exploration" },
  { name: "Castle Siege", tier: 3, type: "Event" },
  { name: "Crystal Wasteland", tier: 3, type: "Traversal" },
  { name: "Dragon's Lair", tier: 3, type: "Exploration" },
  { name: "Megastorm", tier: 3, type: "Event" },
  { name: "Pitched Battle", tier: 3, type: "Event" },
  { name: "Sunken Citadel", tier: 3, type: "Exploration" },
  { name: "Upscale Casino", tier: 3, type: "Social" },
  { name: "Volcanic Eruption", tier: 3, type: "Event" },
  { name: "Chaos Realm", tier: 4, type: "Traversal" },
  { name: "Convergence, City of Portals", tier: 4, type: "Social" },
  { name: "Divine Usurpation", tier: 4, type: "Event" },
  { name: "Imperial Court", tier: 4, type: "Social" },
  { name: "Moon Kingdom", tier: 4, type: "Exploration" },
  { name: "Necromancer's Ossuary", tier: 4, type: "Exploration" },
  { name: "Realm of the Dead", tier: 4, type: "Traversal" },
  { name: "Time Court", tier: 4, type: "Event" },
] as const satisfies readonly EnvironmentReference[];
